version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
  server:
    image: broubroumachine/discount-simultor-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
