#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|build|docs|style|refactor|perf|test|chore|revert)(\(.+?\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message is invalid." >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi
